(cl:defpackage segmentation-srv
  (:use )
  (:export
   "GAZEOPTIMISER"
   "<GAZEOPTIMISER-REQUEST>"
   "GAZEOPTIMISER-REQUEST"
   "<GAZEOPTIMISER-RESPONSE>"
   "GAZEOPTIMISER-RESPONSE"
   "SEG"
   "<SEG-REQUEST>"
   "SEG-REQUEST"
   "<SEG-RESPONSE>"
   "SEG-RESPONSE"
   "GAZEPOINT"
   "<GAZEPOINT-REQUEST>"
   "GAZEPOINT-REQUEST"
   "<GAZEPOINT-RESPONSE>"
   "GAZEPOINT-RESPONSE"
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
  ))

