controller_list:
  - name: ""
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      # - arm_shoulder_1_joint
      # - arm_shoulder_2_joint
      # - arm_elbow_1_joint
      # - arm_elbow_2_joint
