controller_list:
  - name: fake_manipulator_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      # - arm_shoulder_1_joint
      # - arm_shoulder_2_joint
      # - arm_elbow_1_joint
      # - arm_elbow_2_joint
  - name: fake_endeffector_controller
    joints:
      []
