// Generated by gencpp from file segmentation/executionOrderRequest.msg
// DO NOT EDIT!


#ifndef SEGMENTATION_MESSAGE_EXECUTIONORDERREQUEST_H
#define SEGMENTATION_MESSAGE_EXECUTIONORDERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace segmentation
{
template <class ContainerAllocator>
struct executionOrderRequest_
{
  typedef executionOrderRequest_<ContainerAllocator> Type;

  executionOrderRequest_()
    : execute_order(false)  {
    }
  executionOrderRequest_(const ContainerAllocator& _alloc)
    : execute_order(false)  {
  (void)_alloc;
    }



   typedef uint8_t _execute_order_type;
  _execute_order_type execute_order;




  typedef boost::shared_ptr< ::segmentation::executionOrderRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segmentation::executionOrderRequest_<ContainerAllocator> const> ConstPtr;

}; // struct executionOrderRequest_

typedef ::segmentation::executionOrderRequest_<std::allocator<void> > executionOrderRequest;

typedef boost::shared_ptr< ::segmentation::executionOrderRequest > executionOrderRequestPtr;
typedef boost::shared_ptr< ::segmentation::executionOrderRequest const> executionOrderRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segmentation::executionOrderRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segmentation::executionOrderRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace segmentation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::segmentation::executionOrderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segmentation::executionOrderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segmentation::executionOrderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segmentation::executionOrderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segmentation::executionOrderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segmentation::executionOrderRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segmentation::executionOrderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c72f039d49d8fac4896624041a538c0";
  }

  static const char* value(const ::segmentation::executionOrderRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c72f039d49d8facULL;
  static const uint64_t static_value2 = 0x4896624041a538c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::segmentation::executionOrderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segmentation/executionOrderRequest";
  }

  static const char* value(const ::segmentation::executionOrderRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segmentation::executionOrderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool execute_order\n\
";
  }

  static const char* value(const ::segmentation::executionOrderRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segmentation::executionOrderRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.execute_order);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct executionOrderRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segmentation::executionOrderRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segmentation::executionOrderRequest_<ContainerAllocator>& v)
  {
    s << indent << "execute_order: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.execute_order);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGMENTATION_MESSAGE_EXECUTIONORDERREQUEST_H
