// Generated by gencpp from file segmentation/executionOrder.msg
// DO NOT EDIT!


#ifndef SEGMENTATION_MESSAGE_EXECUTIONORDER_H
#define SEGMENTATION_MESSAGE_EXECUTIONORDER_H

#include <ros/service_traits.h>


#include <segmentation/executionOrderRequest.h>
#include <segmentation/executionOrderResponse.h>


namespace segmentation
{

struct executionOrder
{

typedef executionOrderRequest Request;
typedef executionOrderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct executionOrder
} // namespace segmentation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::segmentation::executionOrder > {
  static const char* value()
  {
    return "79dbb0357db7f2c6aa3e8bc9c33c69eb";
  }

  static const char* value(const ::segmentation::executionOrder&) { return value(); }
};

template<>
struct DataType< ::segmentation::executionOrder > {
  static const char* value()
  {
    return "segmentation/executionOrder";
  }

  static const char* value(const ::segmentation::executionOrder&) { return value(); }
};


// service_traits::MD5Sum< ::segmentation::executionOrderRequest> should match 
// service_traits::MD5Sum< ::segmentation::executionOrder > 
template<>
struct MD5Sum< ::segmentation::executionOrderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::segmentation::executionOrder >::value();
  }
  static const char* value(const ::segmentation::executionOrderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::segmentation::executionOrderRequest> should match 
// service_traits::DataType< ::segmentation::executionOrder > 
template<>
struct DataType< ::segmentation::executionOrderRequest>
{
  static const char* value()
  {
    return DataType< ::segmentation::executionOrder >::value();
  }
  static const char* value(const ::segmentation::executionOrderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::segmentation::executionOrderResponse> should match 
// service_traits::MD5Sum< ::segmentation::executionOrder > 
template<>
struct MD5Sum< ::segmentation::executionOrderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::segmentation::executionOrder >::value();
  }
  static const char* value(const ::segmentation::executionOrderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::segmentation::executionOrderResponse> should match 
// service_traits::DataType< ::segmentation::executionOrder > 
template<>
struct DataType< ::segmentation::executionOrderResponse>
{
  static const char* value()
  {
    return DataType< ::segmentation::executionOrder >::value();
  }
  static const char* value(const ::segmentation::executionOrderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEGMENTATION_MESSAGE_EXECUTIONORDER_H
