// Generated by gencpp from file segmentation/gazePointRequest.msg
// DO NOT EDIT!


#ifndef SEGMENTATION_MESSAGE_GAZEPOINTREQUEST_H
#define SEGMENTATION_MESSAGE_GAZEPOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace segmentation
{
template <class ContainerAllocator>
struct gazePointRequest_
{
  typedef gazePointRequest_<ContainerAllocator> Type;

  gazePointRequest_()
    : gaze_x(0.0)
    , gaze_y(0.0)
    , gaze_z(0.0)  {
    }
  gazePointRequest_(const ContainerAllocator& _alloc)
    : gaze_x(0.0)
    , gaze_y(0.0)
    , gaze_z(0.0)  {
  (void)_alloc;
    }



   typedef float _gaze_x_type;
  _gaze_x_type gaze_x;

   typedef float _gaze_y_type;
  _gaze_y_type gaze_y;

   typedef float _gaze_z_type;
  _gaze_z_type gaze_z;




  typedef boost::shared_ptr< ::segmentation::gazePointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segmentation::gazePointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct gazePointRequest_

typedef ::segmentation::gazePointRequest_<std::allocator<void> > gazePointRequest;

typedef boost::shared_ptr< ::segmentation::gazePointRequest > gazePointRequestPtr;
typedef boost::shared_ptr< ::segmentation::gazePointRequest const> gazePointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segmentation::gazePointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segmentation::gazePointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace segmentation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::segmentation::gazePointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segmentation::gazePointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segmentation::gazePointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segmentation::gazePointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segmentation::gazePointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segmentation::gazePointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segmentation::gazePointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8a26852e63a345a4121bd33b86b9edd";
  }

  static const char* value(const ::segmentation::gazePointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8a26852e63a345aULL;
  static const uint64_t static_value2 = 0x4121bd33b86b9eddULL;
};

template<class ContainerAllocator>
struct DataType< ::segmentation::gazePointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segmentation/gazePointRequest";
  }

  static const char* value(const ::segmentation::gazePointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segmentation::gazePointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 gaze_x\n\
float32 gaze_y\n\
float32 gaze_z\n\
";
  }

  static const char* value(const ::segmentation::gazePointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segmentation::gazePointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gaze_x);
      stream.next(m.gaze_y);
      stream.next(m.gaze_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gazePointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segmentation::gazePointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segmentation::gazePointRequest_<ContainerAllocator>& v)
  {
    s << indent << "gaze_x: ";
    Printer<float>::stream(s, indent + "  ", v.gaze_x);
    s << indent << "gaze_y: ";
    Printer<float>::stream(s, indent + "  ", v.gaze_y);
    s << indent << "gaze_z: ";
    Printer<float>::stream(s, indent + "  ", v.gaze_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGMENTATION_MESSAGE_GAZEPOINTREQUEST_H
