// Generated by gencpp from file segmentation/pathPlanner.msg
// DO NOT EDIT!


#ifndef SEGMENTATION_MESSAGE_PATHPLANNER_H
#define SEGMENTATION_MESSAGE_PATHPLANNER_H

#include <ros/service_traits.h>


#include <segmentation/pathPlannerRequest.h>
#include <segmentation/pathPlannerResponse.h>


namespace segmentation
{

struct pathPlanner
{

typedef pathPlannerRequest Request;
typedef pathPlannerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pathPlanner
} // namespace segmentation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::segmentation::pathPlanner > {
  static const char* value()
  {
    return "29b555fe93d25b5dcf4f386d833186f5";
  }

  static const char* value(const ::segmentation::pathPlanner&) { return value(); }
};

template<>
struct DataType< ::segmentation::pathPlanner > {
  static const char* value()
  {
    return "segmentation/pathPlanner";
  }

  static const char* value(const ::segmentation::pathPlanner&) { return value(); }
};


// service_traits::MD5Sum< ::segmentation::pathPlannerRequest> should match 
// service_traits::MD5Sum< ::segmentation::pathPlanner > 
template<>
struct MD5Sum< ::segmentation::pathPlannerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::segmentation::pathPlanner >::value();
  }
  static const char* value(const ::segmentation::pathPlannerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::segmentation::pathPlannerRequest> should match 
// service_traits::DataType< ::segmentation::pathPlanner > 
template<>
struct DataType< ::segmentation::pathPlannerRequest>
{
  static const char* value()
  {
    return DataType< ::segmentation::pathPlanner >::value();
  }
  static const char* value(const ::segmentation::pathPlannerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::segmentation::pathPlannerResponse> should match 
// service_traits::MD5Sum< ::segmentation::pathPlanner > 
template<>
struct MD5Sum< ::segmentation::pathPlannerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::segmentation::pathPlanner >::value();
  }
  static const char* value(const ::segmentation::pathPlannerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::segmentation::pathPlannerResponse> should match 
// service_traits::DataType< ::segmentation::pathPlanner > 
template<>
struct DataType< ::segmentation::pathPlannerResponse>
{
  static const char* value()
  {
    return DataType< ::segmentation::pathPlanner >::value();
  }
  static const char* value(const ::segmentation::pathPlannerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SEGMENTATION_MESSAGE_PATHPLANNER_H
