// Generated by gencpp from file segmentation/pathPlannerRequest.msg
// DO NOT EDIT!


#ifndef SEGMENTATION_MESSAGE_PATHPLANNERREQUEST_H
#define SEGMENTATION_MESSAGE_PATHPLANNERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32MultiArray.h>
#include <geometry_msgs/Point.h>

namespace segmentation
{
template <class ContainerAllocator>
struct pathPlannerRequest_
{
  typedef pathPlannerRequest_<ContainerAllocator> Type;

  pathPlannerRequest_()
    : sorted_objects()
    , target_id(0)
    , grasp_point()  {
    }
  pathPlannerRequest_(const ContainerAllocator& _alloc)
    : sorted_objects(_alloc)
    , target_id(0)
    , grasp_point(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _sorted_objects_type;
  _sorted_objects_type sorted_objects;

   typedef int16_t _target_id_type;
  _target_id_type target_id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _grasp_point_type;
  _grasp_point_type grasp_point;




  typedef boost::shared_ptr< ::segmentation::pathPlannerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segmentation::pathPlannerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct pathPlannerRequest_

typedef ::segmentation::pathPlannerRequest_<std::allocator<void> > pathPlannerRequest;

typedef boost::shared_ptr< ::segmentation::pathPlannerRequest > pathPlannerRequestPtr;
typedef boost::shared_ptr< ::segmentation::pathPlannerRequest const> pathPlannerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segmentation::pathPlannerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segmentation::pathPlannerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace segmentation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::segmentation::pathPlannerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segmentation::pathPlannerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segmentation::pathPlannerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segmentation::pathPlannerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segmentation::pathPlannerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segmentation::pathPlannerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segmentation::pathPlannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d1799e0b491e3c6d6f148bd3d07bda9";
  }

  static const char* value(const ::segmentation::pathPlannerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d1799e0b491e3c6ULL;
  static const uint64_t static_value2 = 0xd6f148bd3d07bda9ULL;
};

template<class ContainerAllocator>
struct DataType< ::segmentation::pathPlannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segmentation/pathPlannerRequest";
  }

  static const char* value(const ::segmentation::pathPlannerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segmentation::pathPlannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32MultiArray sorted_objects\n\
int16 target_id\n\
geometry_msgs/Point grasp_point\n\
\n\
================================================================================\n\
MSG: std_msgs/Float32MultiArray\n\
# Please look at the MultiArrayLayout message definition for\n\
# documentation on all multiarrays.\n\
\n\
MultiArrayLayout  layout        # specification of data layout\n\
float32[]         data          # array of data\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayLayout\n\
# The multiarray declares a generic multi-dimensional array of a\n\
# particular data type.  Dimensions are ordered from outer most\n\
# to inner most.\n\
\n\
MultiArrayDimension[] dim # Array of dimension properties\n\
uint32 data_offset        # padding elements at front of data\n\
\n\
# Accessors should ALWAYS be written in terms of dimension stride\n\
# and specified outer-most dimension first.\n\
# \n\
# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n\
#\n\
# A standard, 3-channel 640x480 image with interleaved color channels\n\
# would be specified as:\n\
#\n\
# dim[0].label  = \"height\"\n\
# dim[0].size   = 480\n\
# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n\
# dim[1].label  = \"width\"\n\
# dim[1].size   = 640\n\
# dim[1].stride = 3*640 = 1920\n\
# dim[2].label  = \"channel\"\n\
# dim[2].size   = 3\n\
# dim[2].stride = 3\n\
#\n\
# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayDimension\n\
string label   # label of given dimension\n\
uint32 size    # size of given dimension (in type units)\n\
uint32 stride  # stride of given dimension\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::segmentation::pathPlannerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segmentation::pathPlannerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sorted_objects);
      stream.next(m.target_id);
      stream.next(m.grasp_point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pathPlannerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segmentation::pathPlannerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segmentation::pathPlannerRequest_<ContainerAllocator>& v)
  {
    s << indent << "sorted_objects: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.sorted_objects);
    s << indent << "target_id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.target_id);
    s << indent << "grasp_point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.grasp_point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGMENTATION_MESSAGE_PATHPLANNERREQUEST_H
